### ISSUE TITLE
Strange Rendering Issue with Qt 5.9

### ISSUE THREAD

**Issue by oracle3001** [dfct/TrueFramelessWindow#4]
The code worked perfectly for Qt 5.8, but upon upgrading to Qt 5.9, I get a strange white box that flickers around the windowless window. You also can't grab the edge of the window and resize it.

![qt_windowless_rendering_issue](https://user-images.githubusercontent.com/20092212/26838497-32d59b0a-4ad8-11e7-85a1-aa062428dd46.png)

**Comment by Snow-Okami** [comment]
I am having the same problem.

**Comment by dfct** [comment]
Thanks for the report & screenshot! I'm looking into this now, will update again later today. Cheers

**Comment by dfct** [comment]
Best I understand now, for anyone stumbling across this with a similar issue in the future, the frameless window hint must be set *before* the window is created by Qt, otherwise it calculates the margins and doesn't ever let that go. In my case, I was setting the hint after calling winId which creates the window.

Qt has some internal mechanisms to otherwise set custom margins with QWindowsWindow::setCustomMargins() and the _q_windowsCustomMargins property, but I'm not sure they're fully implemented / intended to be exposed. I couldn't figure out a way to make use of those.

**Comment by Moussa-Ball** [comment]
But when the window is in full screen mode, it leaves a small border that goes beyond the windows spot bar.

**Comment by dfct** [comment]
@Moussa-Ball , can you open a new issue for the small border beyond the windows task bar? I can't reproduce that on my machine at the moment.
