### ISSUE TITLE
Unable to set Geometry error

### ISSUE THREAD

**Issue by oracle3001** [dfct/TrueFramelessWindow#5]
I have just updated to the use the fix for 5.9, but it seems it has introduced another issue.

Upon running the demo, I get loads of the following errors / warnings.

QWindowsWindow::setGeometry: Unable to set geometry 755x609+0+0 on QWidgetWindow/'QWinWidgetClassWindow'. Resulting geometry:  755x609+973+209 (frame: 0, 0, 0, 0, custom margin: 0, 0, 0, 0, minimum size: 0x0, maximum size: 16777215x16777215).

**Comment by Moussa-Ball** [comment]
But when the window is in full screen mode, it leaves a small border that goes beyond the windows task bar.

**Comment by Snow-Okami** [comment]
I also have this issue and have been trying to debug it. The issue seems to stem from a minimize size not being declared for the window in the traditional way that Qt expects it: 

https://stackoverflow.com/questions/31230975/qt-setgeometry-unable-to-set-geometry

But rather the way it is set currently in qwinwidget (the commented out portion for minimum and maximum window size) does not satisfy it. As you can see in the error, it is saying for the minimum size or the '0+0' part (I believe it to be minimum size - still very new to Qt) is 0 but the resulting minimize was forced to be 973+209, which I am not sure how Qt is calculating internally.

Once we can figure out how to get a proper value fed here, I think it will make Qt happy and end these errors/warnings.

**Comment by Moussa-Ball** [comment]
Yet it works correctly on visual studio with the microsoft compiler.

**Comment by dfct** [comment]
Ugh this is becoming a joke. Just spent another couple hours tracking this down and you'll never guess-- I needed to move `setProperty("_q_embedded_native_parent_handle", (WId)m_ParentNativeWindowHandle);` up two lines. 

As long as that property is set *before* the window is created, then Qt is aware that the widget is embedded in a native window -> the top/left geometry will always 0, 0, and thus, the debug msg complaining goes away.

There's a new debug message now saying enableNonClientDpiScaling failed, but their own GetLastError call is returning 0.. I'm looking at that now.

**Comment by dfct** [comment]
The EnableNonClientDpiScaling debug message appears to be a bug in qwindowscontext.cpp, specifically at line 950:
```
        case QtWindows::NonClientCreate:
            if (QSysInfo::windowsVersion() >= QSysInfo::WV_WINDOWS10 && d->m_creationContext->window->isTopLevel())
                enableNonClientDpiScaling(msg.hwnd);
            return false;
```

The isTopLevel() call is being asked of the base QWindow class, not the QWindowsWindow class. QWindow returns true if parent is null, while QWindowsWindow additionally checks against an embedded bool set via the property mentioned in the comment above ^:
```
bool QWindow::isTopLevel() const
{
    Q_D(const QWindow);
    return d->parentWindow == 0;
}
```
vs
```
 bool QWindowsWindow::isTopLevel() const
{
    return window()->isTopLevel() && !m_data.embedded;
}
```

So for the moment, there's no fix for that debug message. I'll open a bug with Qt. It's harmless otherwise, though..

**Comment by dfct** [comment]
@Moussa-Ball , re: the border extending behind the taskbar, can you open a new issue for that? I can't reproduce that on my machine at the moment, it's working as expected for me currently.

**Comment by dfct** [comment]
Opened [QTBUG-61972](https://bugreports.qt.io/browse/QTBUG-61972) for the debug message about enableNonClientDpiScaling.
